- hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  tasks:
    - name: Retrieve FortiGate system information
      fortinet.fortios.fortios_system_info:
        vdom: "root"
      register: result

    - name: Display system information
      debug:
        var: result
